version: "3"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: "."
      dockerfile: "./api-gateway/Dockerfile"
    depends_on:
      - service-chat
      - service-users
    ports:
      - "7000:7000"
    volumes:
      - ./api-gateway:/opt/app

  service-chat:
    container_name: service-chat
    build:
      context: "."
      dockerfile: "./service-chat/Dockerfile"
    depends_on:
      - service-chat-db
    ports:
      - "3001:3000"
    volumes:
      - ./service-chat:/opt/app
    command: sh -c "yarn watch"

  service-chat-db:
    container_name: service-chat-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: service-chat-db
      PGDATA: /data/pgdata
    volumes:
      - ./db/service-chat:/data/pgdata
    ports:
      - "5433:5432"

  service-users:
    container_name: service-users
    build:
      context: "."
      dockerfile: "./service-users/Dockerfile"
    depends_on:
      - service-users-db
    ports:
      - "3002:3000"
    volumes:
      - ./service-users:/opt/app
    command: sh -c "yarn watch"

  service-users-db:
    container_name: service-users-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: service-users-db
      PGDATA: /data/pgdata
    volumes:
      - ./db/service-users:/data/pgdata
    ports:
      - "5434:5432"
