version: "3"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: "."
      dockerfile: "./api-gateway/Dockerfile"
    depends_on:
      - chat-service
      - users-service
    ports:
      - "7000:7000"
    volumes:
      - ./api-gateway:/opt/app

  chat-service:
    container_name: chat-service
    build:
      context: "."
      dockerfile: "./chat-service/Dockerfile"
    depends_on:
      - chat-service-db
    ports:
      - "3001:3000"
    volumes:
      - ./chat-service:/opt/app
    command: sh -c "yarn watch"

  chat-service-db:
    container_name: chat-service-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chat-service-db
      PGDATA: /data/pgdata
    volumes:
      - ./db/chat-service:/data/pgdata
    ports:
      - "5433:5432"

  users-service:
    container_name: users-service
    build:
      context: "."
      dockerfile: "./users-service/Dockerfile"
    depends_on:
      - users-service-db
    ports:
      - "3002:3000"
    volumes:
      - ./users-service:/opt/app
    command: sh -c "yarn watch"

  users-service-db:
    container_name: users-service-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users-service-db
      PGDATA: /data/pgdata
    volumes:
      - ./db/users-service:/data/pgdata
    ports:
      - "5434:5432"
